services:
  - type: web
    name: breeze-backend
    runtime: docker
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/*.jar
    envVars:
      - key: JAVA_VERSION
        value: 17  # or 21 depending on your project
